import { initializeApp } from "https://www.gstatic.com/firebasejs/12.5.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, signOut, onAuthStateChanged, updateProfile } from "https://www.gstatic.com/firebasejs/12.5.0/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, updateDoc, collection, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.5.0/firebase-firestore.js";
import { getMessaging, getToken, onMessage, isSupported } from "https://www.gstatic.com/firebasejs/12.5.0/firebase-messaging.js";
import { firebaseConfig, ADMIN_EMAIL } from "./firebase-config.js";
import { FCM_VAPID_KEY } from "./fcm-config.js";

const app = initializeApp(firebaseConfig), auth = getAuth(app), db = getFirestore(app);
let currentUser=null, settings=null, currentDayData=null, achievements=[], currentDateKey=localDateKey();
let isSignup=false, editingTaskIndex=null, deferredInstallPrompt=null, serviceWorkerRegistration=null, messaging=null, aiModel=null;
let reminderInterval=null, taskInterval=null, midnightInterval=null;
const $=id=>document.getElementById(id), $$=sel=>Array.from(document.querySelectorAll(sel));

const defaultSettings={wakeTime:"05:00",sleepTime:"23:00",sportTime:"06:30",classStart:"08:00",classEnd:"17:00",moneyGoal:"$100K from YouTube and online skills in 3 years",channels:[{name:"DiraIQ",focus:"Truth behind surroundings. Teach what the world will not teach you: reality, discipline, AI, money, future skills."},{name:"5 Highlight",focus:"Five-minute football highlights. Clean, exciting, globally understandable football recap content."},{name:"GeoMystery",focus:"Geography and mysteries: countries, strange places, maps, unknown facts, and hidden world stories."}],rules:[{title:"Avoid dating for 3 years",text:"Protect focus. No chasing relationships while building your future."},{title:"Avoid useless status posts",text:"No memes or emotional status. Post only important birthdays or serious purpose."},{title:"Work on YouTube until $100K",text:"Research, script, create, edit, upload, learn, and repeat."},{title:"Avoid too much talking and useless groups",text:"Reduce unnecessary words and groups that steal your time."},{title:"Live privately and control emotions",text:"Appear for a short time, work deeply, and use discipline before emotion."}]};
const habits=[["Prayer","fa-sun","10 min"],["Sport","fa-person-running","Body"],["Water","fa-droplet","2.5L"],["Reading","fa-book-open","20 min"],["Focus","fa-brain","Deep work"],["Sleep","fa-moon","11 PM"]];
const coachKeys=[["research","Researched ideas"],["script","Script/writing"],["visuals","Visual plan"],["edit","Editing"],["upload","Upload/schedule"],["competitors","Competitors"]];
const defaultCoach={research:false,script:false,visuals:false,edit:false,upload:false,competitors:false,videoIdea:""};
function localDateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function cleanError(m){return String(m).replace("Firebase: ","").replace(/\(auth\/.*?\)\.?/g,"").trim()}
function isAdminEmail(email){return email?.toLowerCase()===ADMIN_EMAIL.toLowerCase()}
function t(time,title,category="Work"){return{time,title,category,priority:"High",done:false,notifyBeforeDate:"",notifyStartDate:""}}
function buildDefaultHabits(){return{Prayer:false,Sport:false,Water:false,Reading:false,Focus:false,Sleep:false}}
function buildDefaultTasks(type="class"){const s=settings||defaultSettings;if(type==="free")return[t(s.wakeTime,"Wake up. No excuses. No scrolling first.","Personal"),t("05:05","Pray for 10 minutes and ask for strength.","Personal"),t("05:15","Brainstorm today's mission and priorities.","Learning"),t("05:45","Research DiraIQ, 5 Highlight, and GeoMystery ideas.","Learning"),t(s.sportTime,"Sport: push-ups, stretching, body activation.","Health"),t("07:00","Deep work block 1: scripts, research, or coding.","Work"),t("10:00","Deep work block 2: editing or project building.","Work"),t("12:30","Cook, eat, reset focus.","Personal"),t("14:00","Skill improvement and business research.","Learning"),t("17:00","Review money plan and channel progress.","Work"),t("18:00","Editing / content production / cooking dinner.","Work"),t("22:30","Review the day and save achievement.","Personal"),t(s.sleepTime,"Sleep. Protect tomorrow.","Personal")];if(type==="custom")return[t(s.wakeTime,"Wake up and protect the day.","Personal"),t("05:05","Pray for 10 minutes.","Personal"),t("05:30","Write custom agenda for this specific day.","Learning"),t(s.sportTime,"Sport / push-ups.","Health"),t("08:00","Custom important work block.","Work"),t("12:30","Cook, eat, reset.","Personal"),t("18:00","Editing / content production / important evening work.","Work"),t("22:30","Review day and save achievement.","Personal"),t(s.sleepTime,"Sleep on time.","Personal")];return[t(s.wakeTime,"Wake up at 5:00 AM. No excuses.","Personal"),t("05:05","Pray for 10 minutes.","Personal"),t("05:15","Brainstorm today's tasks and discipline mission.","Learning"),t("05:45","Research content ideas for DiraIQ, 5 Highlight, and GeoMystery.","Learning"),t(s.sportTime,"Sport: push-ups / body activation.","Health"),t("07:00","Prepare for university.","Personal"),t(s.classStart,"Attend class / study seriously.","Learning"),t("12:30","Cook, eat, refresh, and return to class if needed.","Personal"),t(s.classEnd,"Finish class and return home.","Learning"),t("18:00","Edit videos / create content / cook dinner.","Work"),t("22:30","Review the day and save achievement.","Personal"),t(s.sleepTime,"Sleep. Protect tomorrow.","Personal")]} 
function buildDefaultReminders(){const s=settings||defaultSettings;return[{time:s.wakeTime,text:"Wake up. Your future needs discipline today.",enabled:true,firedDate:""},{time:"05:05",text:"Prayer time. Ask for strength, then work.",enabled:true,firedDate:""},{time:"05:45",text:"Research content ideas for your 3 channels.",enabled:true,firedDate:""},{time:s.sportTime,text:"Sport time. Push-ups and body activation.",enabled:true,firedDate:""},{time:"18:00",text:"Editing and content production block.",enabled:true,firedDate:""},{time:"22:30",text:"Review the day and finish your achievement.",enabled:true,firedDate:""},{time:s.sleepTime,text:"Sleep. Protect tomorrow.",enabled:true,firedDate:""}]}
function createDayData(type="class",key=localDateKey()){return{date:key,dayType:type,tasks:buildDefaultTasks(type),habits:buildDefaultHabits(),comment:"",mood:"focused",energy:"medium",tomorrowFocus:"",coach:structuredClone(defaultCoach),reminders:buildDefaultReminders(),finished:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function normalizeDay(day){return{...createDayData(day.dayType||"class",day.date||currentDateKey),...day,habits:{...buildDefaultHabits(),...(day.habits||{})},coach:{...structuredClone(defaultCoach),...(day.coach||{})},reminders:day.reminders||buildDefaultReminders()}}
function icon(cat){return{Work:"fa-briefcase",Health:"fa-heart-pulse",Personal:"fa-utensils",Learning:"fa-graduation-cap"}[cat]||"fa-clock"}
function parseMins(v){const m=String(v||"").match(/^(\d{1,2}):(\d{2})$/);if(!m)return null;const h=+m[1],min=+m[2];return h>=0&&h<=23&&min>=0&&min<=59?h*60+min:null}
function getScore(){const total=currentDayData?.tasks?.length||1;return Math.round(currentDayData.tasks.filter(x=>x.done).length/total*100)}
function badge(done,time){if(done)return`<span class="badge done">Done</span>`;const m=parseMins(time),n=new Date(),now=n.getHours()*60+n.getMinutes();return m!==null&&Math.abs(m-now)<=30?`<span class="badge now">Now</span>`:`<span class="badge pending">Pending</span>`}
function downloadText(name,text,type="text/plain;charset=utf-8"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}

$("loginTab").onclick=()=>setAuth(false);$("signupTab").onclick=()=>setAuth(true);function setAuth(s){isSignup=s;$("nameInput").classList.toggle("hidden",!s);$("authSubmit").textContent=s?"Create Admin":"Login";$("signupTab").classList.toggle("active",s);$("loginTab").classList.toggle("active",!s);$("authMessage").textContent=""}
$("authForm").onsubmit=async e=>{e.preventDefault();const email=$("emailInput").value.trim(),pass=$("passwordInput").value.trim(),name=$("nameInput").value.trim()||"Iragena";if(!isAdminEmail(email)){ $("authMessage").textContent=`This private app only accepts ${ADMIN_EMAIL}`;return}try{$("authMessage").textContent="Processing...";if(isSignup){const c=await createUserWithEmailAndPassword(auth,email,pass);await updateProfile(c.user,{displayName:name});await ensureUserDoc(c.user)}else await signInWithEmailAndPassword(auth,email,pass)}catch(err){$("authMessage").textContent=cleanError(err.message)}};
$("resetPasswordBtn").onclick=async()=>{const email=$("emailInput").value.trim();if(!isAdminEmail(email)){ $("authMessage").textContent=`Use ${ADMIN_EMAIL}`;return}try{await sendPasswordResetEmail(auth,email);$("authMessage").textContent="Password reset email sent."}catch(e){$("authMessage").textContent=cleanError(e.message)}};
$("logoutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){$("appShell").classList.add("hidden");$("authScreen").classList.remove("hidden");return}if(!isAdminEmail(user.email)){await signOut(auth);return}$("authScreen").classList.add("hidden");$("appShell").classList.remove("hidden");await registerSW();await ensureUserDoc(user);await loadAllData();renderAll();setupForegroundMessages();startClock();startReminderLoop();startTaskLoop();startMidnightWatcher()});
async function ensureUserDoc(user){const ref=doc(db,"users",user.uid),snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,{name:user.displayName||"Iragena",email:user.email,role:"admin",settings:defaultSettings,createdAt:serverTimestamp()});return}const data=snap.data(),merged={...defaultSettings,...(data.settings||{}),channels:defaultSettings.channels,rules:defaultSettings.rules};await updateDoc(ref,{settings:merged})}
async function loadAllData(){const us=await getDoc(doc(db,"users",currentUser.uid));settings=us.data().settings||defaultSettings;currentDateKey=localDateKey();const ref=doc(db,"users",currentUser.uid,"days",currentDateKey),snap=await getDoc(ref);currentDayData=snap.exists()?normalizeDay(snap.data()):createDayData("class",currentDateKey);if(!snap.exists())await setDoc(ref,currentDayData);await loadAchievements()}
async function saveDay(){currentDayData.updatedAt=new Date().toISOString();await setDoc(doc(db,"users",currentUser.uid,"days",currentDateKey),currentDayData,{merge:true})}
async function loadAchievements(){const snap=await getDocs(collection(db,"users",currentUser.uid,"achievements"));achievements=[];snap.forEach(d=>achievements.push(d.data()));achievements.sort((a,b)=>String(b.date).localeCompare(String(a.date)))}

function renderAll(){renderHeader();renderCalendar();renderTasks();renderHabits();renderChannels();renderCoach();renderAchievements();renderReminders();renderRules();renderSettings();updateBadges()}
function renderHeader(){const d=new Date();$("dateText").textContent=d.toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"});$("welcomeTitle").textContent=`Hi, ${currentUser.displayName||"Iragena"}`;$("dayType").value=currentDayData.dayType||"class";$("dailyComment").value=currentDayData.comment||"";$("moodInput").value=currentDayData.mood||"focused";$("energyInput").value=currentDayData.energy||"medium";$("videoIdeaInput").value=currentDayData.coach.videoIdea||""}
function renderTasks(){currentDayData.tasks.sort((a,b)=>(parseMins(a.time)??9999)-(parseMins(b.time)??9999));const done=currentDayData.tasks.filter(t=>t.done).length,left=currentDayData.tasks.length-done,score=getScore();$("completionScore").textContent=`${score}%`;$("scoreCircle").style.setProperty("--progress",score);$("doneCount").textContent=done;$("leftCount").textContent=left;const next=currentDayData.tasks.find(t=>!t.done);$("nextTaskLine").textContent=`Next focus: ${next?`${next.time} • ${next.title}`:"Complete. Review the day."}`;$("reminderPreview").textContent=next?`Next: ${next.title} at ${next.time}`:"All tasks done. Save your achievement.";$("homeTaskList").innerHTML=currentDayData.tasks.slice(0,4).map((x,i)=>rowHTML(x,i,false)).join("")||`<p class="mini">No tasks yet.</p>`;$("agendaTaskList").innerHTML=currentDayData.tasks.map((x,i)=>rowHTML(x,i,true)).join("");bindTaskButtons()}
function rowHTML(t,i,agenda){const main=`<div class="task-icon"><i class="fa-solid ${icon(t.category)}"></i></div><div class="task-main"><h4>${esc(t.title)}</h4><p>${esc(t.category||"Work")} • ${esc(t.time||"--")}</p></div>${badge(t.done,t.time)}`;if(agenda)return`<div class="task-row agenda-row" data-i="${i}"><span class="agenda-time">${esc(t.time||"--")}</span>${main}<div class="row-actions"><button class="toggle-task" type="button"><i class="fa-solid fa-check"></i> ${t.done?"Undo":"Done"}</button><button class="edit-task" type="button"><i class="fa-solid fa-pen"></i> Edit</button><button class="delete delete-task" type="button"><i class="fa-solid fa-trash"></i> Delete</button></div></div>`;return`<div class="task-row" data-i="${i}">${main}<div class="row-actions"><button class="toggle-task" type="button"><i class="fa-solid fa-check"></i> ${t.done?"Undo":"Done"}</button><button class="edit-task" type="button"><i class="fa-solid fa-pen"></i> Edit</button></div></div>`}
function bindTaskButtons(){$$(".toggle-task").forEach(b=>b.onclick=async()=>{const i=+b.closest(".task-row").dataset.i;currentDayData.tasks[i].done=!currentDayData.tasks[i].done;await saveDay();renderAll()});$$(".edit-task").forEach(b=>b.onclick=()=>openTaskModal(+b.closest(".task-row").dataset.i));$$(".delete-task").forEach(b=>b.onclick=async()=>{const i=+b.closest(".task-row").dataset.i;if(!confirm("Delete this activity?"))return;currentDayData.tasks.splice(i,1);await saveDay();renderAll()})}
function renderHabits(){$("quickHabitPills").innerHTML=habits.map(([n,ic])=>`<button class="habit-pill ${currentDayData.habits[n]?"active":""}" data-h="${n}" type="button"><i class="fa-solid ${ic}"></i> ${n}</button>`).join("");$("habitGrid").innerHTML=habits.map(([n,ic,sub])=>`<button class="habit-check ${currentDayData.habits[n]?"active":""}" data-h="${n}" type="button"><i class="fa-solid ${ic}"></i><strong>${n}</strong><small>${sub}</small></button>`).join("");$$(".habit-pill,.habit-check").forEach(b=>b.onclick=async()=>{currentDayData.habits[b.dataset.h]=!currentDayData.habits[b.dataset.h];await saveDay();renderHabits();renderStats()});renderStats()}
function renderStats(){const total=habits.length,done=habits.filter(([n])=>currentDayData.habits[n]).length,focus=Math.round(done/total*100),water=currentDayData.habits.Water?100:40;$("streakCount").textContent=calcStreak();$("focusScore").textContent=`${focus}%`;$("focusPercent2").textContent=`${focus}%`;$("waterPercent").textContent=`${water}%`;$("focusBar").style.setProperty("--value",`${focus}%`);$("waterBar").style.setProperty("--value",`${water}%`);$("heatmap").innerHTML=[1,3,2,4,1,3,4,2,4,3,1,2,4,3].map(n=>`<span class="heat-day h${n}"></span>`).join("")}
function renderChannels(){$("channelList").innerHTML=settings.channels.map(c=>`<section class="channel-card"><h4>${esc(c.name)}</h4><p>${esc(c.focus)}</p></section>`).join("")}
function renderCoach(){$("coachGrid").innerHTML=coachKeys.map(([k,l])=>`<label class="coach-item"><input class="coach-check" type="checkbox" data-k="${k}" ${currentDayData.coach[k]?"checked":""}> ${l}</label>`).join("");$$(".coach-check").forEach(c=>c.onchange=async()=>{currentDayData.coach[c.dataset.k]=c.checked;await saveDay();renderCoachMessage()});renderCoachMessage()}
function renderCoachMessage(){const d=coachKeys.filter(([k])=>currentDayData.coach[k]).length;$("channelMotivationBox").textContent=d>=5?"Excellent channel execution today. Repeat this pattern tomorrow.":d>=3?"Good progress. Add one more serious content action tomorrow.":d>=1?"You touched the mission lightly. Protect a full content block tomorrow.":"No channel progress saved yet. Your future audience cannot find work you never create."}
function renderAchievements(){if(!achievements.length){$("achievementList").innerHTML=`<p class="mini">No achievements saved yet. Finish your first day.</p>`;return}$("achievementList").innerHTML=achievements.slice(0,6).map(a=>`<section class="achievement-card"><h4><i class="fa-solid fa-trophy"></i> ${esc(a.date)} • ${+a.score||0}%</h4><p>${+a.completedCount||0} completed • ${+a.missedCount||0} missed • ${esc(a.mood||"normal")}</p><p>${esc(a.advice||"")}</p></section>`).join("")}
function renderReminders(){$("reminderList").innerHTML=(currentDayData.reminders||[]).map((r,i)=>`<div class="reminder-row" data-i="${i}"><input class="reminder-toggle" type="checkbox" ${r.enabled?"checked":""}><span class="reminder-time">${esc(r.time)}</span><span class="reminder-text">${esc(r.text)}</span><button class="icon-mini delete-reminder" type="button"><i class="fa-solid fa-trash"></i></button></div>`).join("");$$(".reminder-toggle").forEach(e=>e.onchange=async()=>{const i=+e.closest(".reminder-row").dataset.i;currentDayData.reminders[i].enabled=e.checked;await saveDay()});$$(".delete-reminder").forEach(b=>b.onclick=async()=>{const i=+b.closest(".reminder-row").dataset.i;currentDayData.reminders.splice(i,1);await saveDay();renderReminders()})}
function renderRules(){$("rulesList").innerHTML=settings.rules.map(r=>`<section class="rule-card"><h4>${esc(r.title)}</h4><p>${esc(r.text)}</p></section>`).join("")}
function renderSettings(){$("wakeTimeInput").value=settings.wakeTime;$("sleepTimeInput").value=settings.sleepTime;$("sportTimeInput").value=settings.sportTime;$("classStartInput").value=settings.classStart;$("classEndInput").value=settings.classEnd;$("moneyGoalInput").value=settings.moneyGoal}
function renderCalendar(){const d=new Date(),today=d.getDate();$("monthLabel").textContent=d.toLocaleDateString("en-US",{month:"long",year:"numeric"});$("miniCalendar").innerHTML=["SU","MO","TU","WE","TH","FR","SA"].map(x=>`<span>${x}</span>`).concat(Array.from({length:28},(_,i)=>`<button class="${i+1===today?"today":""}" type="button">${i+1}</button>`)).join("")}
function calcStreak(){if(!achievements.length)return currentDayData.finished?1:0;const s=new Set(achievements.map(a=>a.date));if(currentDayData.finished)s.add(currentDateKey);let n=0,d=new Date();while(s.has(localDateKey(d))){n++;d.setDate(d.getDate()-1)}return n}

$$(".nav").forEach(b=>b.onclick=()=>showView(b.dataset.screen));$$(".nav-go").forEach(b=>b.onclick=()=>showView(b.dataset.go));function showView(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".nav").forEach(b=>b.classList.toggle("active",b.dataset.screen===id))}
$("fabBtn").onclick=()=>openTaskModal();$("openTaskModalBtn").onclick=()=>openTaskModal();$("closeModalBtn").onclick=closeTaskModal;$("cancelEditBtn").onclick=closeTaskModal;$("taskModal").onclick=e=>{if(e.target.id==="taskModal")closeTaskModal()};$$(".choice").forEach(b=>b.onclick=()=>{const g=b.closest(".choices");g.querySelectorAll(".choice").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
function openTaskModal(i=null){editingTaskIndex=i;const task=i!==null?currentDayData.tasks[i]:null;$("taskModalTitle").innerHTML=task?`<i class="fa-solid fa-pen"></i> Edit Activity`:`<i class="fa-solid fa-plus"></i> Add Activity`;$("taskTitleInput").value=task?.title||"";$("taskTimeInput").value=task?.time||"08:00";setChoice("category",task?.category||"Work");setChoice("priority",task?.priority||"High");$("cancelEditBtn").classList.toggle("hidden",i===null);$("taskModal").classList.add("open")}
function closeTaskModal(){$("taskModal").classList.remove("open");editingTaskIndex=null;$("taskForm").reset()}function setChoice(g,v){$$(`[data-choice="${g}"] .choice`).forEach(b=>b.classList.toggle("active",b.dataset.value===v))}function getChoice(g){return $(`[data-choice="${g}"] .choice.active`)?.dataset.value||""}
$("taskForm").onsubmit=async e=>{e.preventDefault();const old=editingTaskIndex!==null?currentDayData.tasks[editingTaskIndex]:{};const task={time:$("taskTimeInput").value,title:$("taskTitleInput").value.trim(),category:getChoice("category"),priority:getChoice("priority"),done:editingTaskIndex!==null?old.done:false,notifyBeforeDate:old.notifyBeforeDate||"",notifyStartDate:old.notifyStartDate||""};if(editingTaskIndex!==null)currentDayData.tasks[editingTaskIndex]=task;else currentDayData.tasks.push(task);await saveDay();closeTaskModal();renderAll();showView("agendaScreen")};
$("generateAgendaBtn").onclick=async()=>{currentDayData.dayType=$("dayType").value;currentDayData.tasks=buildDefaultTasks(currentDayData.dayType);await saveDay();renderAll()};$("resetTodayBtn").onclick=async()=>{if(!confirm("Reset today to default agenda?"))return;currentDayData=createDayData($("dayType").value||"class",currentDateKey);await saveDay();renderAll()};$("saveReflectionBtn").onclick=async()=>{currentDayData.comment=$("dailyComment").value.trim();currentDayData.mood=$("moodInput").value;currentDayData.energy=$("energyInput").value;await saveDay();$("saveStatus").textContent="Reflection saved.";setTimeout(()=>$("saveStatus").textContent="",1800)};$("saveCoachBtn").onclick=async()=>{currentDayData.coach.videoIdea=$("videoIdeaInput").value.trim();$$(".coach-check").forEach(c=>currentDayData.coach[c.dataset.k]=c.checked);await saveDay();renderCoachMessage()};
$("finishDayBtn").onclick=async()=>{currentDayData.comment=$("dailyComment").value.trim();currentDayData.mood=$("moodInput").value;currentDayData.energy=$("energyInput").value;currentDayData.finished=true;const a=buildAchievement();await setDoc(doc(db,"users",currentUser.uid,"achievements",currentDateKey),a,{merge:true});await saveDay();await loadAchievements();renderAll();showView("goalsScreen")};
function buildAchievement(){const c=currentDayData.tasks.filter(t=>t.done),m=currentDayData.tasks.filter(t=>!t.done);return{date:currentDateKey,score:getScore(),completedCount:c.length,missedCount:m.length,completedTasks:c.map(t=>t.title),missedTasks:m.map(t=>t.title),comment:currentDayData.comment||"",mood:currentDayData.mood||"normal",energy:currentDayData.energy||"medium",coach:currentDayData.coach,advice:adviceText(getScore()),createdAt:new Date().toISOString()}}
function adviceText(s){return s>=85?"Strong execution. Repeat this structure tomorrow and protect your morning.":s>=65?"Good movement, but not full control. Tomorrow, protect the first 3 hours.":s>=40?"Execution was weak. Reduce phone checking and complete one serious content task early.":"Warning day. Tomorrow: wake, pray, research one idea, sport, and complete one content action."}
$("downloadTodayBtn").onclick=()=>downloadText(`daily-roadmap-${currentDateKey}.txt`,dayReport(currentDayData));$("downloadArchiveBtn").onclick=()=>downloadText("daily-roadmap-achievements.json",JSON.stringify(achievements,null,2),"application/json");$("downloadAllCSVBtn").onclick=()=>{const rows=[["date","score","completed","missed","mood","energy","comment"]];achievements.forEach(a=>rows.push([a.date,a.score,a.completedCount||0,a.missedCount||0,a.mood||"",a.energy||"",a.comment||""]));downloadText("daily-roadmap-achievements.csv",rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv;charset=utf-8")};
function dayReport(day){const done=day.tasks.filter(t=>t.done).map(t=>`✓ ${t.time} - ${t.title}`).join("\n"),miss=day.tasks.filter(t=>!t.done).map(t=>`✗ ${t.time} - ${t.title}`).join("\n");return`MY DAILY ROADMAP REPORT\nDate: ${currentDateKey}\nScore: ${getScore()}%\nMood: ${day.mood}\nEnergy: ${day.energy}\n\nCOMPLETED\n${done||"None"}\n\nMISSED\n${miss||"None"}\n\nREFLECTION\n${day.comment||""}\n`}
$("addDefaultRemindersBtn").onclick=async()=>{currentDayData.reminders=buildDefaultReminders();await saveDay();renderReminders()};$("addReminderForm").onsubmit=async e=>{e.preventDefault();currentDayData.reminders.push({time:$("reminderTimeInput").value,text:$("reminderTextInput").value.trim(),enabled:true,firedDate:""});$("reminderTimeInput").value="";$("reminderTextInput").value="";await saveDay();renderReminders()};
$("enableNotificationsBtn").onclick=async()=>{if(!("Notification"in window)){ $("notificationStatus").textContent="Notifications not supported.";return}const p=await Notification.requestPermission();$("notificationStatus").textContent=p==="granted"?"Browser notifications enabled.":"Notifications blocked."};$("sendTestLocalBtn").onclick=async()=>{if(!("Notification"in window)){ $("pushStatus").textContent="Notifications not supported.";return}const p=await Notification.requestPermission();if(p!=="granted"){ $("pushStatus").textContent="Allow notifications first.";return}new Notification("Daily Roadmap Reminder",{body:"Test lock-screen notification.",icon:"./icon-192.png",badge:"./badge-72.png",requireInteraction:true});$("pushStatus").textContent="Test notification sent."};
function showReminder(text){updateBadges(true);if("Notification"in window&&Notification.permission==="granted")new Notification("Daily Roadmap Reminder",{body:text,icon:"./icon-192.png",badge:"./badge-72.png",requireInteraction:true});else alert(`Reminder: ${text}`)}
function startReminderLoop(){clearInterval(reminderInterval);reminderInterval=setInterval(async()=>{const today=localDateKey(),time=new Date().toTimeString().slice(0,5);let ch=false;for(const r of currentDayData.reminders||[]){if(r.enabled&&r.firedDate!==today&&r.time===time){showReminder(r.text);r.firedDate=today;ch=true}}if(ch){await saveDay();renderReminders()}},30000)}
function startTaskLoop(){clearInterval(taskInterval);taskInterval=setInterval(async()=>{const today=localDateKey(),n=new Date(),now=n.getHours()*60+n.getMinutes();let ch=false;for(const task of currentDayData.tasks||[]){if(task.done)continue;const m=parseMins(task.time);if(m===null)continue;const diff=m-now;if(diff<=5&&diff>=1&&task.notifyBeforeDate!==today){showReminder(`Next activity in ${diff} minute(s): ${task.title}`);task.notifyBeforeDate=today;ch=true}if(diff<=0&&diff>=-1&&task.notifyStartDate!==today){showReminder(`Start now: ${task.title}`);task.notifyStartDate=today;ch=true}}if(ch){await saveDay();renderAll()}},30000)}
function updateBadges(force=false){const over=force||currentDayData?.tasks?.some(t=>!t.done&&parseMins(t.time)!==null&&parseMins(t.time)<(new Date().getHours()*60+new Date().getMinutes()));$$(".bell-dot").forEach(b=>b.classList.toggle("has-overdue",!!over))}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e});$("installAppBtn").onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$("pushStatus").textContent="Install prompt completed."}else $("pushStatus").textContent="Use browser menu: Add to Home screen / Install app."};
async function registerSW(){if(!("serviceWorker"in navigator))return null;try{serviceWorkerRegistration=await navigator.serviceWorker.register("./firebase-messaging-sw.js");return serviceWorkerRegistration}catch(e){console.warn("SW failed",e);return null}}
$("enablePushBtn").onclick=enablePush;async function enablePush(){try{if(!FCM_VAPID_KEY||FCM_VAPID_KEY.includes("PASTE_")){ $("pushStatus").textContent="Paste Web Push certificate key in fcm-config.js first.";return}if(!await isSupported()){ $("pushStatus").textContent="FCM not supported on this browser/device.";return}const p=await Notification.requestPermission();if(p!=="granted"){ $("pushStatus").textContent="Notifications blocked.";return}if(!serviceWorkerRegistration)serviceWorkerRegistration=await registerSW();messaging=getMessaging(app);const token=await getToken(messaging,{vapidKey:FCM_VAPID_KEY,serviceWorkerRegistration});if(!token){$("pushStatus").textContent="No token received.";return}$("fcmTokenBox").value=token;await setDoc(doc(db,"users",currentUser.uid,"fcmTokens",token),{token,userAgent:navigator.userAgent,platform:navigator.platform||"",updatedAt:new Date().toISOString()},{merge:true});$("pushStatus").textContent="Push notifications enabled and token saved."}catch(e){$("pushStatus").textContent="Push setup error: "+cleanError(e.message||e)}}
$("copyTokenBtn").onclick=async()=>{if(!$("fcmTokenBox").value){$("pushStatus").textContent="No token to copy.";return}await navigator.clipboard.writeText($("fcmTokenBox").value);$("pushStatus").textContent="Token copied."};async function setupForegroundMessages(){try{if(!await isSupported())return;messaging=getMessaging(app);onMessage(messaging,p=>{const title=p?.notification?.title||"Daily Roadmap Reminder",body=p?.notification?.body||p?.data?.body||"You have a reminder.";if("Notification"in window&&Notification.permission==="granted")new Notification(title,{body,icon:"./icon-192.png",badge:"./badge-72.png",requireInteraction:true});else alert(`${title}: ${body}`)})}catch(e){console.warn(e)}}
$("aiDailyReviewBtn").onclick=()=>runAI("daily");$("aiTomorrowPlanBtn").onclick=()=>runAI("tomorrow");$("aiChannelCoachBtn").onclick=()=>runAI("channel");$("aiWeeklyReviewBtn").onclick=()=>runAI("weekly");async function getAIModel(){if(aiModel)return aiModel;const m=await import("https://www.gstatic.com/firebasejs/12.5.0/firebase-ai.js");const ai=m.getAI(app,{backend:new m.GoogleAIBackend()});aiModel=m.getGenerativeModel(ai,{model:"gemini-2.5-flash"});return aiModel}
async function runAI(type){const box=$("aiOutputBox");box.className="ai-output loading";box.textContent="Gemini AI is thinking...";try{const model=await getAIModel();const res=await Promise.race([model.generateContent(promptText(type)),new Promise((_,rej)=>setTimeout(()=>rej(new Error("AI request timed out after 25 seconds.")),25000))]);const text=res?.response?.text?.()||"No AI response received.";box.className="ai-output";box.textContent=text;await setDoc(doc(db,"users",currentUser.uid,"aiResponses",`${currentDateKey}-${type}`),{type,date:currentDateKey,text,createdAt:new Date().toISOString()},{merge:true})}catch(e){box.className="ai-output error";box.textContent=`${fallbackAI(type)}\n\nTechnical note: ${cleanError(e.message||e)}`}}
function promptText(type){const c=currentDayData.tasks.filter(t=>t.done).map(t=>t.title),m=currentDayData.tasks.filter(t=>!t.done).map(t=>t.title);const base=`You are a strict but constructive discipline coach for Iragena. Mission: ${settings.moneyGoal}. Routine: sleep 11 PM, wake 5 AM, prayer, brainstorming, content research, sport, university/class when available, evening editing/cooking, review. Channels: DiraIQ = truth behind surroundings and what the world will not teach you; 5 Highlight = five-minute football highlights; GeoMystery = geography and mysteries. Rules: avoid dating 3 years, avoid useless status/memes, avoid too much talking/groups, live privately, control emotions, focus on YouTube until $100K in 3 years. Today score ${getScore()}%. Mood ${currentDayData.mood}. Energy ${currentDayData.energy}. Reflection: ${currentDayData.comment||"none"}. Completed: ${c.join("; ")||"none"}. Missed: ${m.join("; ")||"none"}. Channel progress: ${JSON.stringify(currentDayData.coach)}. Recent achievements: ${JSON.stringify(achievements.slice(0,7))}. Be direct, short, practical, motivational. Use English with a little Kinyarwanda only where useful.`;if(type==="tomorrow")return base+" Give tomorrow plan: warning, first 3 hours, each channel action, one thing to avoid, command.";if(type==="channel")return base+" Give channel growth coaching for DiraIQ, 5 Highlight, and GeoMystery.";if(type==="weekly")return base+" Analyze weekly pattern, strongest habit, weakest habit, weekly improvement system, 5-line discipline message.";return base+" Give today review: score interpretation, biggest weakness, best win, tomorrow advice, YouTube motivation, sentence before sleeping."}
function fallbackAI(type){if(type==="channel")return"DiraIQ needs one truth-based idea. 5 Highlight needs one football highlight plan. GeoMystery needs one mysterious geography topic. Do not wait to feel ready.";if(type==="tomorrow")return"Tomorrow: wake up, pray, research one idea, do sport, and finish one real YouTube action before distractions.";if(type==="weekly")return"Your week improves when your mornings improve. Protect wake-up, prayer, research, sport, and evening review.";return adviceText(getScore())}
$("settingsForm").onsubmit=async e=>{e.preventDefault();settings.wakeTime=$("wakeTimeInput").value||"05:00";settings.sleepTime=$("sleepTimeInput").value||"23:00";settings.sportTime=$("sportTimeInput").value||"06:30";settings.classStart=$("classStartInput").value||"08:00";settings.classEnd=$("classEndInput").value||"17:00";settings.moneyGoal=$("moneyGoalInput").value.trim();settings.channels=defaultSettings.channels;settings.rules=defaultSettings.rules;await updateDoc(doc(db,"users",currentUser.uid),{settings});currentDayData.tasks=buildDefaultTasks(currentDayData.dayType||"class");currentDayData.reminders=buildDefaultReminders();await saveDay();$("settingsStatus").textContent="Settings saved.";setTimeout(()=>$("settingsStatus").textContent="",1800);renderAll()};
function startMidnightWatcher(){clearInterval(midnightInterval);midnightInterval=setInterval(async()=>{const key=localDateKey();if(key!==currentDateKey){currentDateKey=key;await loadAllData();renderAll();showReminder("New day created. Your roadmap reset to default agenda.")}},60000)}function startClock(){const tick=()=>{$("clockText").textContent=new Date().toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"})};tick();setInterval(tick,30000)}
